blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/rizsotto/Bear/discussions
    about: Ask questions, share ideas, or discuss usage in Discussions.
